<a href="https://colab.research.google.com/github/Siddharth5723/python_for_ml/blob/main/Data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
data = [1,2,3,4,5]
series = pd.Series(data)
print("series \n", series)

series
 0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
#Creating a series from a dictionary

data = {"a" : 1 , "b" : 2 , "c" : 3}
series_dict = pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data = [10,20,30]
index = ["a" , "b" , "c"]
pd.Series(data , index)

a    10
b    20
c    30
dtype: int64

In [9]:
##Dataframe creation
data = {
    'Name' : ['Siddharth' , 'Nikhil' , 'Titli'],
    'Age' : [21 , 21, 20],
    'city' : ['jaipur' , "sikar" , "jaipur"]

}

df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age    city
0  Siddharth   21  jaipur
1     Nikhil   21   sikar
2      Titli   20  jaipur
<class 'pandas.core.frame.DataFrame'>

In [13]:
import numpy as np
arr = np.array(df)
print(arr)

[['Siddharth' 21 'jaipur']
 ['Nikhil' 21 'sikar']
 ['Titli' 20 'jaipur']]

In [14]:
## creating a dataframe form a list of dictionaries

data = [
    {'Name' : 'Siddharth', 'Age' : 21 , "City" : "Jaipur"},
    {'Name' : 'Nikhil', 'Age' : 21 , "City" : "Sikar"},
    {'Name' : 'Sidd', 'Age' : 24 , "City" : "Jodhpur"},
    {'Name' : 'Titli', 'Age' : 20 , "City" : "Jaipur"},
]

df = pd.DataFrame(data)
print(df)
print(type(df))

        Name  Age     City
0  Siddharth   21   Jaipur
1     Nikhil   21    Sikar
2       Sidd   24  Jodhpur
3      Titli   20   Jaipur
<class 'pandas.core.frame.DataFrame'>

In [16]:
df['Name']

0    Siddharth
1       Nikhil
2         Sidd
3        Titli
Name: Name, dtype: object

In [23]:
df.iloc[0][2]

/tmp/ipykernel_2475/2519637664.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][2]

'Jaipur'

In [24]:
# Acessing a specified element
df.at[2 , 'Age']

np.int64(24)

In [25]:
df.iat[2,2]

'Jodhpur'

In [26]:
#Data manipulation with Dataframe
df

        Name  Age     City
0  Siddharth   21   Jaipur
1     Nikhil   21    Sikar
2       Sidd   24  Jodhpur
3      Titli   20   Jaipur

In [28]:
df['Salary'] = [50000 , 60000 , 70000 , 80000 ]
df

        Name  Age     City  Salary
0  Siddharth   21   Jaipur   50000
1     Nikhil   21    Sikar   60000
2       Sidd   24  Jodhpur   70000
3      Titli   20   Jaipur   80000

In [34]:
#Remove a column
df.drop('Salary', axis=1 , inplace = True)

In [35]:
df

        Name  Age     City
0  Siddharth   21   Jaipur
1     Nikhil   21    Sikar
2       Sidd   24  Jodhpur
3      Titli   20   Jaipur

In [36]:
df.describe()

             Age
count   4.000000
mean   21.500000
std     1.732051
min    20.000000
25%    20.750000
50%    21.000000
75%    21.750000
max    24.000000

In [37]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data", header = None)

In [38]:
df.head(5)

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [43]:
df.drop(4 , axis = 1 , inplace = True)

In [44]:
df.head()

     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2
3  4.6  3.1  1.5  0.2
5  5.4  3.9  1.7  0.4